apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.resourcePrefix }}app-init
  annotations:
    helm.sh/hook: "post-install"
spec:
  template:
    spec:
      containers:
      - name: app-init
        enableServiceLinks: false
        env:
        {{ range $key, $value := .Values.docker.services.console.environment }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{ end }}
        {{- if .Values.docker.services.console.environment_secrets }}
        envFrom:
          - secretRef:
              name: {{ .Values.resourcePrefix }}console
        {{- end }}
        image: {{ .Values.docker.image.console }}
        imagePullPolicy: Always
        command: ["app", "init"]
      imagePullSecrets:
      - name: {{ .Values.resourcePrefix }}docker-config
      restartPolicy: Never
