apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.resourcePrefix }}app-migrate
  annotations:
    helm.sh/hook: "post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  template:
    spec:
      containers:
      - name: app-migrate
        enableServiceLinks: false
        env:
        {{ range $key, $value := .Values.docker.services.console.environment }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{ end }}
        image: {{ .Values.docker.image.console }}
        imagePullPolicy: Always
        command: ["app", "migrate"]
      imagePullSecrets:
      - name: {{ .Values.resourcePrefix }}docker-config
      restartPolicy: Never
