{{ with .Values.services.console -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Values.resourcePrefix }}app-migrate
  annotations:
    helm.sh/hook: "post-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"
    argocd.argoproj.io/hook: "Sync"
    argocd.argoproj.io/hook-delete-policy: "BeforeHookCreation"
    argocd.argoproj.io/sync-wave: "10"
spec:
  template:
    spec:
      containers:
      - name: app-migrate
        enableServiceLinks: false
        env:
        {{ range $key, $value := .environment }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{ end }}
        {{- if .environment_secrets }}
        envFrom:
          - secretRef:
              name: {{ $.Values.resourcePrefix }}console
        {{- end }}
        image: {{ .image | quote }}
        imagePullPolicy: Always
        command: ["app", "migrate"]
      imagePullSecrets:
      - name: {{ $.Values.resourcePrefix }}docker-config
      restartPolicy: Never
{{- end }}
