apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.resourcePrefix }}app-init
  annotations:
    helm.sh/hook: "post-install"
spec:
  template:
    spec:
      containers:
      - env:
        {{ range $key, $value := .Values.docker.services.console.environment }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{ end }}
        image: {{ .Values.docker.image.console }}
        imagePullPolicy: Always
        name: app-init
        command: ["app", "init"]
      imagePullSecrets:
      - name: {{ .Values.resourcePrefix }}docker-config
      restartPolicy: Never
