{{ if .Values.service.mysql }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}mysql
  labels:
    app.service: {{ .Values.prefix }}mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: {{ .Values.prefix }}mysql
  template:
    metadata:
      labels:
        app.service: {{ .Values.prefix }}mysql
    spec:
      containers:
      - env:
        {{ range $key, $value := .Values.docker.services.mysql.environment }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{ end }}
        image: mysql:5.7
        imagePullPolicy: Always
        name: mysql
        args:
        - --ignore-db-dir
        - lost+found
        ports:
        - containerPort: 3306
        resources: {}
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: {{ .Values.prefix }}mysql-persistent-storage
          mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
      - name: {{ .Values.prefix }}mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.prefix }}mysql-pv-claim
status: {}
{{ end }}
