apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app.service: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: keycloak
  template:
    metadata:
      labels:
        app.service: keycloak
    spec:
      containers:
      - env:
          {{ range $key, $value := .Values.environment }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
          {{ end }}
        image: {{ .Values.docker.image.keycloak }}
        imagePullPolicy: Always
        name: keycloak
        ports:
        - containerPort: 9000
        resources: {}
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: docker-config
      restartPolicy: Always
status: {}
