apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app.service: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: keycloak
  template:
    metadata:
      labels:
        app.service: keycloak
    spec:
      containers:
      - image: {{ .Values.docker.image.keycloak }}
        imagePullPolicy: Always
        name: keycloak
        ports:
        - containerPort: 8080
        resources: {}
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        {{ range $key, $value := .Values.environment }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{ end }}
      imagePullSecrets:
      - name: docker-config
      restartPolicy: Always
status: {}
