apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resourcePrefix }}keycloak
  labels:
    app.service: {{ .Values.resourcePrefix }}keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: {{ .Values.resourcePrefix }}keycloak
  template:
    metadata:
      labels:
        app.service: {{ .Values.resourcePrefix }}keycloak
    spec:
      containers:
      - env:
        {{ range $key, $value := .Values.docker.services.keycloak.environment }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{ end }}
        image: {{ .Values.docker.image.keycloak }}
        imagePullPolicy: Always
        name: keycloak
        ports:
        - containerPort: 8080
        resources: {}
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: {{ .Values.resourcePrefix }}docker-config
      restartPolicy: Always
status: {}
