{{ with .Values.services.keycloak -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.resourcePrefix }}keycloak
  labels:
    app.service: {{ $.Values.resourcePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.service: {{ $.Values.resourcePrefix }}keycloak
  template:
    metadata:
      labels:
        app.service: {{ $.Values.resourcePrefix }}keycloak
    spec:
      containers:
      - name: keycloak
        enableServiceLinks: false
        env:
        {{ range $key, $value := .environment }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{ end }}
        {{- if .environment_secrets }}
        envFrom:
          - secretRef:
              name: {{ $.Values.resourcePrefix }}keycloak
        {{- end }}
        image: {{ .image | quote }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        resources: {}
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
{{- if $.Values.docker.image_pull_config }}
      imagePullSecrets:
      - name: {{ $.Values.resourcePrefix }}image-pull-config
{{- end }}
      restartPolicy: Always
status: {}
{{- end }}
