{{ if eq .Values.ingress "standard" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.service: {{ .Values.resourcePrefix }}keycloak
  name: {{ .Values.resourcePrefix }}keycloak
spec:
  rules:
  - host: {{ .Values.services.console.environment.APP_HOST }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.resourcePrefix }}keycloak
          servicePort: 8080
status:
  loadBalancer: {}
{{ end }}
