{{ if eq .Values.ingress "standard" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- with .Values.services.keycloak.ingress.annotations }}
  annotations: {{ . | toYaml | nindent 4 }}
{{- end }}
  creationTimestamp: null
  labels:
    app.service: {{ .Values.resourcePrefix }}keycloak
  name: {{ .Values.resourcePrefix }}keycloak
spec:
  {{- with (pick .Values.ingress "ingressClassName" "tls") }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  rules:
  - host: {{ .Values.services.console.environment.APP_HOST }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.resourcePrefix }}keycloak
            port:
              number: 8080
status:
  loadBalancer: {}
{{ end }}
