{{ if eq .Values.ingress "standard" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.service: keycloak
  name: keycloak
spec:
  rules:
  - host: {{ .Values.docker.services.keycloak.environment.KEYCLOAK_HOSTNAME }}
    http:
      paths:
      - backend:
          serviceName: keycloak
          servicePort: 8080
status:
  loadBalancer: {}
{{ end }}
