{{ if eq .Values.ingress "istio" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: {{ .Release.Namespace }}-{{ .Values.resourcePrefix }}keycloak-virtualservice
 labels:
   app: {{ .Values.resourcePrefix }}keycloak
   app.service: {{ .Values.resourcePrefix }}keycloak
spec:
 hosts:
 - {{ .Values.services.console.environment.APP_HOST }}
 gateways:
{{- range $key, $value := .Values.istio.gateways }}
 - {{ tpl $value $ | quote }}
{{- end }}
 http:
 - route:
   - destination:
       host: {{ .Values.resourcePrefix }}keycloak
       port:
         number: 8080
{{ end }}
