{{ if eq .Values.ingress "istio" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: {{ .Release.Namespace }}-{{ .Values.prefix }}keycloak-virtualservice
 labels:
   app: {{ .Values.prefix }}keycloak
   app.service: {{ .Values.prefix }}keycloak
spec:
 hosts:
 - {{ .Values.docker.services.keycloak.environment.KEYCLOAK_HOSTNAME }}
 gateways:
 - istio-system/{{ .Release.Namespace }}-gateway
 http:
 - route:
   - destination:
       host: {{ .Values.prefix }}keycloak
       port:
         number: 8080
{{ end }}
