{{- if .Values.prometheus.podMonitoring -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.resourcePrefix }}keycloak
  labels:
    app.service: {{ .Values.resourcePrefix }}keycloak
spec:
  selector:
    matchLabels:
      app.service: {{ .Values.resourcePrefix }}keycloak
  podMetricsEndpoints:
{{- if .Values.services.keycloak.metricsEnabled -}}
{{ .Values.services.keycloak.metricsEndpoints | toYaml | nindent 6 -}}
{{- end -}}
{{- end -}}
