apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: {{ .Values.resourcePrefix }}keycloak
  name: {{ .Values.resourcePrefix }}keycloak
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app.service: {{ .Values.resourcePrefix }}keycloak
status:
  loadBalancer: {}