apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: keycloak
  name: keycloak
spec:
  ports:
  - name: "8080"
    port: 80
    targetPort: 8080
  selector:
    app.service: keycloak
status:
  loadBalancer: {}