version: '2.3'
services:
  cfssl:
    build: ./cfssl/
    expose:
     - '8888'
  keycloak:
    build: ./keycloak/
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: keycloak
      DB_VENDOR: mysql
      DB_USER: keycloak
      DB_PASSWORD: password
    volumes:
      - './keycloak/themes/poc:/opt/jboss/keycloak/themes/poc'
      - './keycloak/realms:/opt/jboss/keycloak/realms'
    ports:
      - '8080:8080'
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: correctbatterystaplehorse
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: ~
