{{ with .Values.services.console -}}
{{ if .enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.resourcePrefix }}console
  labels:
    app.service: {{ $.Values.resourcePrefix }}console
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.service: {{ $.Values.resourcePrefix }}console
  template:
    metadata:
      labels:
        app.service: {{ $.Values.resourcePrefix }}console
    spec:
      containers:
      - env:
        {{ range $key, $value := .environment }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{ end }}
        {{- if .environment_secrets }}
        envFrom:
          - secretRef:
              name: {{ $.Values.resourcePrefix }}console
        {{- end }}
        image: {{ .image | quote }}
        imagePullPolicy: Always
        name: console
        resources: {}
        readinessProbe:
          exec:
            command:
            - app
            - state
          initialDelaySeconds: 20
          periodSeconds: 10
{{- if $.Values.docker.image_pull_config }}
      imagePullSecrets:
      - name: {{ $.Values.resourcePrefix }}image-pull-config
{{- end }}
      restartPolicy: Always

status: {}
{{- end }}
{{- end }}
