command('app build'):
  env:
    COMPOSE_PROJECT_NAME: = @('namespace')
  exec: |
    #!bash(workspace:/)|@
    passthru docker-compose build

command('app build <service>'):
  env:
    COMPOSE_PROJECT_NAME: = @('namespace')
    SERVICE: = input.argument('service')
  exec: |
    #!bash(workspace:/)|@
    passthru docker-compose build "$SERVICE"
