command('app build'):
  env:
    COMPOSE_PROJECT_NAME: = @('namespace')
    LOGIN_ON_BUILD: "= @('docker.build.login') ? 'true' : 'false'"
  exec: |
    #!bash(workspace:/)|@
    [ "$LOGIN_ON_BUILD" != "true" ] || echo "@('docker.password')" | run docker login --username="@('docker.username')" --password-stdin @('docker.repository')
    ws external-images pull
    passthru docker-compose build
    [ "$LOGIN_ON_BUILD" != "true" ] || run docker logout @('docker.repository')

command('app build <service>'):
  env:
    COMPOSE_PROJECT_NAME: = @('namespace')
    SERVICE: = input.argument('service')
  exec: |
    #!bash(workspace:/)|@
    passthru docker-compose build "$SERVICE"
