
confd('harness:/'):
  - { src: docker/image/console/Dockerfile }
  - { src: docker/image/console/root/home/build/.my.cnf }
  - { src: docker/image/console/root/lib/task/assets/apply.sh }
  - { src: docker/image/console/root/lib/task/assets/dump.sh }
  - { src: docker/image/console/root/lib/task/build/frontend.sh }
  - { src: docker/image/console/root/lib/task/build/backend.sh }
  - { src: docker/image/console/root/lib/task/database/available.sh }
  - { src: docker/image/console/root/lib/task/init.sh }
  - { src: docker/image/console/root/lib/task/install.sh }
  - { src: docker/image/console/root/lib/task/migrate.sh }
  - { src: docker/image/keycloak/Dockerfile }
  - { src: application/overlay/Jenkinsfile }
  - { src: application/overlay/.dockerignore, dst: workspace:/.dockerignore }
  - { src: application/skeleton/README.md }
  - { src: docker-compose.yml, dst: workspace:/docker-compose.yml }
  - { src: docker-sync.yml, dst: workspace:/docker-sync.yml }
  - { src: helm/app/values.yaml }
