command('app publish'): |
  #!bash(workspace:/)|@
  echo "@('docker.password')" | run docker login --username="@('docker.username')" --password-stdin @('docker.repository')
  run docker push @('docker.repository'):@('app.version')-console
  run docker push @('docker.repository'):@('app.version')-keycloak
  run docker logout @('docker.repository')

command('app deploy <environment>'):
  env:
    ENVIRONMENT: = input.argument('environment')
    NAMESPACE:   = @('pipeline.' ~ input.argument('environment') ~ '.namespace')
    CLUSTER:     = @('pipeline.' ~ input.argument('environment') ~ '.cluster.name')
    TIMEOUT:     = @('helm.timeout')
  exec: |
    #!bash(harness:/helm)|=
    cd "${ENVIRONMENT}"
    doctl -t $DO_ACCESS_TOKEN kubernetes cluster kubeconfig show $CLUSTER > kubectl.config.yaml
    passthru helm init --client-only
    passthru helm dependency build
    passthru helm --kubeconfig=$PWD/kubectl.config.yaml upgrade --wait --install --timeout "${TIMEOUT}" --namespace "${NAMESPACE}" "${NAMESPACE}" ./

command('helm kubeval <chart-path>'):
  env:
    CHART_PATH: = input.argument('chart-path')
    NAMESPACE: = @('pipeline.' ~ input.argument('environment') ~ '.namespace')
  exec: |
    #!bash(harness:/helm)|=
    cd "${CHART_PATH}"
    passthru helm init --client-only
    passthru helm dependency build
    passthru helm plugin install https://github.com/instrumenta/helm-kubeval || true
    passthru helm kubeval .
