FROM {{ @('docker.image.keycloak') }}

COPY ./standalone/configuration/ /opt/jboss/keycloak/standalone/configuration/
COPY ./.my127ws/docker/image/keycloak/docker-override-entrypoint.sh /opt/jboss/tools/

ENTRYPOINT ["/opt/jboss/tools/docker-override-entrypoint.sh"]
CMD ["-b", "0.0.0.0"]
