FROM {{ @('docker.image.keycloak') }}

{% if @('keycloak.plugins.keycloak-metrics-spi') %}
ADD --chown=jboss:jboss https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar /opt/jboss/keycloak/standalone/deployments/
{% endif %}
COPY ./standalone/configuration/ /opt/jboss/keycloak/standalone/configuration/
COPY ./.my127ws/docker/image/keycloak/docker-override-entrypoint.sh /opt/jboss/tools/

ENTRYPOINT ["/opt/jboss/tools/docker-override-entrypoint.sh"]
CMD ["-b", "0.0.0.0"]
